package org.example
package fields

object FieldsZacksFC {
  val identifiers = Seq(
    RowIdentifier("M_TICKER",	"Zacks Identifier, ticker or trading symbol"),
    RowIdentifier("TICKER",	"Ticker or trading symbol"),
    RowIdentifier("COMP_NAME"	, "Company name"),
    RowIdentifier("COMP_NAME_2"	, "DEPRECATED"),
    RowIdentifier("EXCHANGE"	, "Exchange traded"),
    RowIdentifier("CURRENCY_CODE"	, "Currency code"),
    RowIdentifier("PER_END_DATE"	, "Period end date"),
    RowIdentifier("PER_TYPE"	, "Period type"),
    RowIdentifier("PER_CODE", "DEPRECATED"),
    RowIdentifier("PER_FISC_YEAR"	, "Period fiscal year"),
    RowIdentifier("PER_FISC_QTR", "Period fiscal quarter"),
    RowIdentifier("PER_CAL_YEAR", "	Period calendar year"),
    RowIdentifier("PER_CAL_QTR"	, "Period calendar quarter"),
  )

  val textualColumns = Seq(
    TextField("DATA_TYPE_IND", "Data type indicator: E = Empty, F = Full filing, P = Preliminary",	"Data type indicator: E = Empty, F = Full filing, P = Preliminary"),
    TextField("FILING_TYPE", "Filing type: 10-K, 10-Q, PRELIM", "Indicates whether the data in this record is empty, or comes from the preliminary earnings report or the full SEC 10K/Q filing."),
    TextField("QTR_NBR", "Quarter number", "The number of the fiscal quarter in reference to the current fiscal year (Q1, Q2, Q3 or Q4)"),
    TextField("ZACKS_SECTOR_CODE",	"Zacks sector code", "Zacks sector code"),
    TextField("ZACKS_X_IND_CODE",	"Zacks expanded industry code",	"Zacks expanded industry code"),
    TextField("ZACKS_METRICS_IND_CODE", "Zacks metrics industry code	Zacks", "metrics industry code"),
    TextField("FYE_MONTH",	"Fiscal year end month number",	"Fiscal year end month number"),
    TextField("COMP_CIK", "Company Central Index Key (CIK)", "Company Central Index Key (CIK)"),
    TextField("PER_LEN",	"Period length",	"the length of the reporting period in months."),
    TextField("SIC_CODE",	"Standard Industrial Classification (SIC) 4-character code",	"Standard Industrial Classification (SIC) 4-character code"),
    TextField("FILING_DATE",	"Filing date",	"Original date of statement filing with the SEC"),
    TextField("LAST_CHANGED_DATE",	"Last changed date",	"Date that the data was last restated."),
    TextField("STATE_INCORP_NAME",	"State name of company incorpration",	"State in which the company is incorporated"),
    TextField("BUS_ADDRESS_LINE_1",	"Business address line 1",	"Business address line 1 from SEC reports"),
    TextField("BUS_CITY",	"Business city",	"Business city from SEC reports"),
    TextField("BUS_STATE_NAME",	"Business state name",	"Business state name from SEC reports"),
    TextField("BUS_POST_CODE",	"Business postal or zip code",	"Business postal or zip code from SEC reports"),
    TextField("BUS_PHONE_NBR",	"Business phone number",	"Business phone number from SEC reports"),
    TextField("BUS_FAX_NBR",	"Business fax number",	"Business fax number from SEC reports"),
    TextField("MAIL_ADDRESS_LINE_1",	"Mail address line 1",	"Mail address line 1 from SEC reports"),
    TextField("MAIL_CITY",	"Mail city",	"Mail city from SEC reports"),
    TextField("MAIL_STATE_NAME",	"Mail state name",	"Mail state name from SEC reports"),
    TextField("MAIL_POST_CODE",	"Mail postal or zip code",	"Mail postal or zip code from SEC reports"),
    TextField("COUNTRY_NAME",	 "Country name",	"Name of home country"),
    TextField("COUNTRY_CODE",	 "Country code", "Code for home country"),
    TextField("HOME_EXCHANGE_NAME",	"Home exchange name (ADR)",	"Name of the home exchange traded if not in the U.S."),
    TextField("EMP_CNT", "Total number of employees",	"Total number of employees"),
    TextField("EMP_PT_CNT", "Total number of part-time employees",	"Total number of part-time employees"),
    TextField("EMP_FT_CNT",	"Total number of full-time employees",	"Total number of full-time employees"),
    TextField("EMP_OTHER_CNT",	"Total number of other employees",	"Total number of other employees"),
    TextField("COMM_SHARE_HOLDER",	"Common share holders of record",	"Number of common shareholders of record"),
    TextField("AUDITOR",	"Auditor",	"Name of the accounting firm that audits the company's financial statements"),
    TextField("AUDITOR_OPINION",	"Auditor's opinion",	"Auditor's opinion of the reliability of the financial statements and the company's ability to remain in business as a going concern."),
    TextField("COMP_URL",	"Company web address",	"Company web address"),
    TextField("EMAIL_ADDR",	"Company e-mail address",	"Company e-mail address, usually leads to the investor relations department"),
    TextField("NBR_SHARES_OUT",	"Number of shares outstanding",	"Number of shares outstanding reported on the face of the SEC report. THIS COLUMN IS DEPRECATED. DO NOT USE."),
    TextField("SHARES_OUT_DATE",	"Shares outstanding date",	"Shares outstanding as of date. THIS COLUMN IS DEPRECATED. DO NOT USE."),
    TextField("OFFICER_NAME_1",	"Officer name 1",	"Officer name 1 (Officers are ranked according to title - CEO, the Presiden, the CFO, etc.)"),
    TextField("OFFICER_TITLE_1",	"Officer title 1",	"Officer title 1"),
    TextField("OFFICER_NAME_2",	"Officer name 2",	"Officer name 2 (Officers are ranked according to title - CEO, the Presiden, the CFO, etc.)"),
    TextField("OFFICER_TITLE_2",	"Officer title 2",	"Officer title 2"),
    TextField("OFFICER_NAME_3",	"Officer name 3",	"Officer name 3 (Officers are ranked according to title - CEO, the Presiden, the CFO, etc.)"),
    TextField("OFFICER_TITLE_3",	"Officer title 3",	"Officer title 3"),
    TextField("OFFICER_NAME_4",	"Officer name 4",	"Officer name 4 (Officers are ranked according to title - CEO, the Presiden, the CFO, etc.)"),
    TextField("OFFICER_TITLE_4",	"Officer title 4",	"Officer title 4"),
    TextField("OFFICER_NAME_5",	"Officer name 5",	"Officer name 5 (Officers are ranked according to title - CEO, the Presiden, the CFO, etc.)"),
    TextField("OFFICER_TITLE_5",	"Officer title 5",	"Officer title 5"),
    TextField("RPT_0_DATE",	"Section 0 report date",	"Date that the income statement was submitted to the SEC, or last revised if restated"),
    TextField("RPT_1_DATE",	"Section 1 report date",	"Date that the balance sheet was submitted to the SEC, or last revised if restated"),
    TextField("RPT_2_DATE",	"Section 2 report date",	"Date that the cash flow statement was submitted to the SEC, or last revised if restated"),
  )

  val indicators = Seq(
    IndicatorField("Income Statement",	"TOT_REVNU",	"Total revenue",	"The sum of all revenue fields included for a company's operating activities.",	"Millions"),
    IndicatorField("Income Statement",	"COST_GOOD_SOLD",	"Cost of goods sold",	"The difference between beginning and ending inventories for tangible products resulting in an expense that reflects production and sales costs.",	"Millions"),
    IndicatorField("Income Statement",	"GROSS_PROFIT",	"Gross profit",	"Revenues from operations less the associated costs.",	"Millions"),
    IndicatorField("Income Statement",	"TOT_DEPREC_AMORT",	"Total depreciation and amortization",	"The sum of all depreciation and amortization items from the income statement.",	"Millions"),
    IndicatorField("Income Statement",	"INT_EXP_OPER",	"Interest expense - Operating",	"Interest paid on loans that are deemed to be necessary to support operating activities",	"Millions"),
    IndicatorField("Income Statement",	"INT_INVST_INCOME_OPER",	"Interest/investment income - Operating", "Interest income from loans made, or income related to investments made, as a normal part of daily operations",	"Millions"),
    IndicatorField("Income Statement",	"RES_DEV_EXP",	"Research and development expenses",	"An expense arising from studies and product development processes.",	"Millions"),
    IndicatorField("Income Statement",	"IN_PROC_RES_DEV_EXP_AGGR",	"In-process research and development expenses - aggregate",	"Incomplete research and development costs from acquired companies.",	"Millions"),
    IndicatorField("Income Statement",	"TOT_SELL_GEN_ADMIN_EXP",	"Total selling, general, and administrative expenses",	"The sum of all selling, general and administrative expenses.",	"Millions"),
    IndicatorField("Income Statement",	"RENTAL_EXP_IND_BROKER",	"Rental expense for industry or brokerage",	"Expenses for the rental of equipment or facilities.",	"Millions"),
    IndicatorField("Income Statement",	"PENSION_POST_RETIRE_EXP",	"Pension and post-retirement expense",	"The net amount of expenses paid for employee retirement benefits.",	"Millions"),
    IndicatorField("Income Statement",	"OTHER_OPER_INCOME_EXP",	"Other operating income or expenses",	"The aggregate amount of all operating expenses either too small to report separately or that cannot be standardized into another Zacks field.",	"Millions"),
    IndicatorField("Income Statement",	"TOT_OPER_EXP",	"Total operating expenses",	"The sum of all operating expenses for the given industry.",	"Millions"),
    IndicatorField("Income Statement",	"OPER_INCOME",	"Operating income",	"The income after operating expenses",	"Millions"),
    IndicatorField("Income Statement",	"NON_OPER_INT_EXP",	"Non-operating interest expenses",	"The costs incurred by borrowings for the given period.",	"Millions"),
    IndicatorField("Income Statement",	"INT_CAP",	"Interest capitalized",	"Interest expense that has been capitalized as an asset and is amortized over a defined period.",	"Millions"),
    IndicatorField("Income Statement",	"ASSET_WDOWN_IMPAIR_AGGR",	"Asset writedowns and impairments - aggregate",	"An expense incurred when the carrying value of an asset is greater than its fair value and it is written down or decreased in value to equal its current fair value.",	"Millions"),
    IndicatorField("Income Statement",	"RESTRUCT_CHARGE",	"Restructuring charges",	"Expenses incurred from reorganizing a company's internal operational architecture or debt structure.",	"Millions"),
    IndicatorField("Income Statement",	"MERGER_ACQ_INCOME_AGGR",	"Merger or acquisition related income/expense - aggregate",	"Expenses related to corporate actions including mergers, acquisitions and spin-offs.",	"Millions"),
    IndicatorField("Income Statement",	"RENTAL_INCOME",	"Rental income",	"Ancillary income derived from rental of assets not currently used in operations",	"Millions"),
    IndicatorField("Income Statement",	"SPCL_UNUSUAL_CHARGE",	"Special and unusual charges",	"Expense incurred for charges that are deemed to be special or non-recurring.",	"Millions"),
    IndicatorField("Income Statement",	"IMPAIR_GOODWILL",	"Impairment of goodwill", "A charge off occurring when the carrying value of goodwill is less than its market value. When this happens the goodwill is written off so that its carrying value matches up with its market value.",	"Millions"),
    IndicatorField("Income Statement",	"LITIG_AGGR",	"Litigation - aggregate",	"Income or expenses associated with legal matters including settlements, patents and provisions for future legal costs.",	"Millions"),
    IndicatorField("Income Statement",	"GAIN_LOSS_SALE_ASSET_AGGR",	"Gain/loss from sale of assets - aggregate",	"An increase or decrease in income arising from the sale of assets.",	"Millions"),
    IndicatorField("Income Statement",	"GAIN_LOSS_SALE_INVST_AGGR",	"Gain/loss from sale of investments - aggregate",	"Net losses or gains arising from the sale of equity investments, securities and/or derivative assets.",	"Millions"),
    IndicatorField("Income Statement",	"STOCK_DIV_SUBSID",	"Stock dividends of subsidiary",	"Dividend requirements of subsidiary entities.",	"Millions"),
    IndicatorField("Income Statement",	"INCOME_LOSS_EQUITY_INVST_OTHER",	"Income loss from equity investments - Other",	"Income or loss earned from a 20%-50% investment in a company. For these types of investments, the net income of the investee effects the net income of the investor company.",	"Millions"),
    IndicatorField("Income Statement",	"PRE_TAX_MINORITY_INT",	"Pre-tax minority interest",	"A pre-tax figure denoting the reporting company's share of ownership in another company by including income or loss of the company as a portion of Net Income",	"Millions"),
    IndicatorField("Income Statement",	"INT_INVST_INCOME",	"Interest and investment income",	"Income earned from deposits at financial institutions or dividends from investments",	"Millions"),
    IndicatorField("Income Statement",	"OTHER_NON_OPER_INCOME_EXP",	"Other non-operating income/expense",	"The aggregate amount of all non-operating expenses either too small to report separately or that cannot be standardized into another Zacks field.",	"Millions"),
    IndicatorField("Income Statement",	"TOT_NON_OPER_INCOME_EXP",	"Total non-operating income/expense",	"The sum of all non-operating expenses for the given industry.",	"Millions"),
    IndicatorField("Income Statement",	"PRE_TAX_INCOME",	"Pre-tax", "income	Company's earnings or loss before taxes on income have been accounted for.",	"Millions"),
    IndicatorField("Income Statement",	"TOT_PROVSN_INCOME_TAX",	"Total provision for income taxes",	"The total amount of income tax expense for the given period.",	"Millions"),
    IndicatorField("Income Statement",	"INCOME_AFT_TAX",	"Income after taxes",	"Earnings or losses after income tax expense but before minority interest, extraordinary items, discontinued operations, preferred dividends and accounting changes have been accounted for.",	"Millions"),
    IndicatorField("Income Statement",	"MINORITY_INT",	"Minority interest",	"The reporting company's share of ownership in another company by including income or loss of the company as a portion of Net Income",	"Millions"),
    IndicatorField("Income Statement",	"EQUITY_EARN_SUBSID",	"Equity in earnings of subsidiary",	"A company's income or loss from investments in affiliated companies.",	"Millions"),
    IndicatorField("Income Statement",	"INVST_GAIN_LOSS_OTHER",	"Investment gain/loss - Other",	"Non-cash gains and losses from revaluations of held investments. Also includes cash gains and losses from the sale of investments.",	"Millions"),
    IndicatorField("Income Statement",	"OTHER_INCOME",	"Other income",	"Any post tax miscellaneous income items.",	"Millions"),
    IndicatorField("Income Statement",	"INCOME_CONT_OPER",	"Income from continuous operations",	"A company's total income or loss before discontinued operations, extraordinary items, preferred stock dividends and accounting change",	"Millions"),
    IndicatorField("Income Statement",	"INCOME_DISCONT_OPER",	"Income from discontinued operations",	"Income or loss from the complete discontinuation of a segment or business, net of associated taxes and fees.",	"Millions"),
    IndicatorField("Income Statement",	"INCOME_BEF_EXORD_ACCT_CHANGE",	"Income before extraordindary income and accounting change",	"A company's total income or loss before extraordinary items, preferred stock dividends and accounting change",	"Millions"),
    IndicatorField("Income Statement",	"EXORD_INCOME_LOSS",	"Extraordinary income/loss",	"Income or loss net of associated taxes from a non-recurring situation that passes the tests of materiality, frequency, and business scope. A full description of the event(s) comprising extraordinary income is given in the financial statement footnotes.",	"Millions"),
    IndicatorField("Income Statement",	"CUMUL_EFF_ACCT_CHANGE",	"Cumulative effect of accounting change",	"The effect that the usage of a new accounting principle has on the current and prior periods. This value is net of tax effects.",	"Millions"),
    IndicatorField("Income Statement",	"CONSOL_NET_INCOME_LOSS",	"Consolidated net income/loss",	"A company's total income or loss before preferred stock dividends",	"Millions"),
    IndicatorField("Income Statement",	"NON_CTL_INT",	"Non-controlling interest",	"The reporting company's share of ownership in another company by including income or loss of the company as a portion of Net Income",	"Millions"),
    IndicatorField("Income Statement",	"NET_INCOME_PARENT_COMP",	"Net income attributable to parent company",	"A company's total income or loss before preferred stock dividends, and after removing Non-Controlling Interest",	"Millions"),
    IndicatorField("Income Statement",	"PREF_STOCK_DIV_OTHER_ADJ",	"Preferred stock dividend and other adjustments",	"An expense arising from the payment of dividends to preferred shareholders. Also includes any miscellaneous expense or income items.",	"Millions"),
    IndicatorField("Income Statement",	"NET_INCOME_LOSS_SHARE_HOLDER",	"Net income/loss available to common share holders",	"Company's net profit or loss after all revenues, income items, and expenses have been accounted for. Because this figure is given after preferred dividend expense, it the net income value allotted to common shareholders.",	"Millions"),
    IndicatorField("Income Statement",	"EPS_BASIC_CONT_OPER",	"Earnings per share (EPS) (basic) from continuous operations",	"Company's net earnings or losses from continuing operations on a per basic share basis.",	"Actual $"),
    IndicatorField("Income Statement",	"EPS_BASIC_DISCONT_OPER",	"Earnings per share (EPS) (basic) from discontinued operations",	"Company's net earnings or losses from discontinued operations on a per basic share basis.",	"Actual $"),
    IndicatorField("Income Statement",	"EPS_BASIC_ACCT_CHANGE",	"Earnings per share (EPS) (basic) from accounting change",	"Company's net earnings or losses from a change in accounting principles on a per basic share basis.",	"Actual $"),
    IndicatorField("Income Statement",	"EPS_BASIC_EXTRA",	"Earnings per share (EPS) (basic) from extras",	"Company's net earnings or losses from extraordinary on a per basic share basis.",	"Actual $"),
    IndicatorField("Income Statement",	"EPS_BASIC_CONSOL",	"Earnings per share (EPS) (basic) consolidated",	"Company's net earnings or losses including non-controlling interest, before preferred dividends, on a per basic share basis.",	"Actual $"),
    IndicatorField("Income Statement",	"EPS_BASIC_PARENT_COMP",	"Earnings per share (EPS) (basic) from the parent company",	"Company's net earnings or losses excluding non-controlling interest, before preferred dividends, on a per basic share basis.",	"Actual $"),
    IndicatorField("Income Statement",	"BASIC_NET_EPS",	"Basic net earnings per share (EPS)",	"Company's net earnings or losses attributable to common shareholders per basic share basis.", "Actual $"),
    IndicatorField("Income Statement",	"EPS_DILUTED_CONT_OPER",	"Earnings per share (EPS) (diluted) from continuous operations",	"Company's net earnings or losses from continuing operations on a per diluted share basis.",	"Actual $"),
    IndicatorField("Income Statement",	"EPS_DILUTED_DISCONT_OPER",	"Earnings per share (EPS) (diluted) from discontinued operations",	"Company's net earnings or losses from discontinued operations on a per diluted share basis.",	"Actual $"),
    IndicatorField("Income Statement",	"EPS_DILUTED_ACCT_CHANGE",	"Earnings per share (EPS) (diluted) from accounting change",	"Company's net earnings or losses from a change in accounting principles on a per diluted share basis.",	"Actual $"),
    IndicatorField("Income Statement",	"EPS_DILUTED_EXTRA",	"Earnings per share (EPS) (diluted) from extras",	"Company's net earnings or losses from extraordinary on a per diluted share basis.",	"Actual $"),
    IndicatorField("Income Statement",	"EPS_DILUTED_CONSOL",	"Earnings per share (EPS) (diluted) consolidated",	"Company's net earnings or losses including non-controlling interest, before preferred dividends, on a per diluted share basis.",	"Actual $"),
    IndicatorField("Income Statement",	"EPS_DILUTED_PARENT_COMP",	"Earnings per share (EPS) (diluted) parent company",	"Company's net earnings or losses excluding non-controlling interest, before preferred dividends, on a per diluted share basis.",	"Actual $"),
    IndicatorField("Income Statement",	"DILUTED_NET_EPS",	"Diluted net earnings per share (EPS)",	"Company's net earnings or losses attributable to common shareholders per diluted share basis which includes all convertible securities and debt, options and warrants.",	"Actual $"),
    IndicatorField("Income Statement",	"DILUTION_FACTOR",	"Dilution factor",	"The per share value of all items such as convertible debt, securities, warrants and options that are assumed converted to calculate diluted shares.",	"Millions"),
    IndicatorField("Income Statement",	"NORM_PRE_TAX_INCOME",	"Normalized pre-tax income",	"A company's income before income tax expense smoothed out by removing non-recurring items.",	"Millions"),
    IndicatorField("Income Statement",	"NORM_AFT_TAX_INCOME",	"Normalized income after tax",	"A company's after tax profit or loss smoothed out by elimination of all non-recurring items.",	"Millions"),
    IndicatorField("Income Statement",	"EBITDA",	"Earnings before interest, taxes, depreciation, and amortization (EBITDA)",	"Income before interest, taxes, depreciation and amortization.",	"Millions"),
    IndicatorField("Income Statement",	"EBIT",	"Earnings before interest and taxes (EBIT)",	"Income before interest and taxes",	"Millions"),
    IndicatorField("Income Statement",	"WAVG_SHARES_OUT",	"Weighted-average shares outstanding (basic)",	"The number of shares held by shareholders including insiders but not including a company's treasury shares, sourced from the company 10-K or 10-Q SEC reports.",	"Millions"),
    IndicatorField("Income Statement",	"WAVG_SHARES_OUT_DILUTED",	"Weighted-average shares outstanding (diluted)",	"The number of shares held by shareholders including insiders but not including a company's treasury shares assuming conversion of all convertible debt, securities, warrants and options, sourced from the company 10-K or 10-Q SEC reports.",	"Millions"),
    IndicatorField("Income Statement",	"EPS_BASIC_NET",	"Earnings per share (EPS) (basic) net",	"A company's net earnings or losses attributable to common shareholders per basic share basis.",	"Actual $"),
    IndicatorField("Income Statement",	"EPS_DILUTED_NET",	"Earnings per share (EPS) (diluted) net",	"A company's net earnings or losses attributable to common shareholders per diluted share baswhich includes all convertible securities and debt, options and warrants.",	"Actual $"),
    IndicatorField("Balance Sheet",	"CASH_STERM_INVST",	"Cash and short-term investments",	"Cash deposits at financial institutions that can immediately be withdrawn at any time, and investments maturing in one year or less that are highly liquid and therefore regarded as cash equivalents and reported with or near cash line items. Cash equivalents are extremely liquid investments with low risk that can immediately be converted to cash. Includes cash restricted for specified purposes.",	"Millions"),
    IndicatorField("Balance Sheet",	"NOTE_LOAN_RCV",	"Notes and loans receivable",	"Current receivables created by lending money through notes and loans to third parties with maturities of less than 1 year, or a portion due in less than 1 year. This figure is captured at net value. If a gross value is given (primarily for loans receivable) the calculated allowance for uncollectable amounts is captured as well.",	"Millions"),
    IndicatorField("Balance Sheet",	"RCV_EST_DOUBT",	"Receivables estimated doubtful",	"The calculated value of receivables that are deemed to be uncollectible.",	"Millions"),
    IndicatorField("Balance Sheet",	"RCV_TOT",	"Receivables - Total",	"The total amount of collectibles for a company",	"Millions"),
    IndicatorField("Balance Sheet",	"INVTY",	"Inventory",	"The total value of inventories in all stages of completion.",	"Millions"),
    IndicatorField("Balance Sheet",	"PREPAID_EXPENSE",	"Pre-paid expenses",	"A current asset created by prepayment of costs and expenses for which the benefits will occur at a future date.",	"Millions"),
    IndicatorField("Balance Sheet",	"DEF_CHARGE_CURR",	"Deferred charges - Current",	"A current asset arising from costs that have been paid where the benefits are deferred to a later date.",	"Millions"),
    IndicatorField("Balance Sheet",	"DEF_TAX_ASSET_CURR",	"Deferred tax assets - Current",	"An asset creating by a difference between accounting for income tax purposes and financial reporting purposes",	"Millions"),
    IndicatorField("Balance Sheet",	"ASSET_DISCONT_OPER_CURR",	"Assets of discontinued operations - Current",	"The aggregate value of current assets from business segments that a company has disposed of or wants to dispose of in the near future.",	"Millions"),
    IndicatorField("Balance Sheet",	"OTHER_CURR_ASSET",	"Other current assets",	"Field containing the sum of all current assets that cannot be standardized into another field as well as those that are aggregated by the company because materially, they are too small to list separately.",	"Millions"),
    IndicatorField("Balance Sheet",	"TOT_CURR_ASSET",	"Total current assets",	"The sum of all assets that are classified as current because they will provide a benefit within one year.",	"Millions"),
    IndicatorField("Balance Sheet",	"GROSS_PROP_PLANT_EQUIP",	"Gross - Property, plant, and equipment",	"The sum of all gross property, plant & Equipment fields. Where companies do not report a break down of plant, property, & equipment, the value is entered in this field alone.",	"Millions"),
    IndicatorField("Balance Sheet",	"TOT_ACCUM_DEPREC",	"Total accumulated depreciation and depletion",	"Aggregate amount subtracted from the value of an asset or assets to reflect its usage over time and how much value could be recouped if the asset was sold.",	"Millions"),
    IndicatorField("Balance Sheet",	"NET_PROP_PLANT_EQUIP",	"Net - Property, plant, and equipment",	"The sum of all net property, plant & Equipment fields. Where companies do not report a break down of plant, property, & equipment, the value is entered in this field alone.",	"Millions"),
    IndicatorField("Balance Sheet",	"NET_REAL_ESTATE_MISC_PROP",	"Net - Real estate and miscellaneous property",	"Real estate and other properties reported separately from other plant, property and equipment fields.",	"Millions"),
    IndicatorField("Balance Sheet",	"CAP_SOFTWARE",	"Capitalized software",	"Software and software development costs that are capitalized into an asset and amortized over time. This field is used if capitalized software is not included in plant, property and equipment line items.",	"Millions"),
    IndicatorField("Balance Sheet",	"LTERM_INVST",	"Long-term investments",	"The aggregate value of debt and or equity investments with maturities or benefits lasting more than one year.",	"Millions"),
    IndicatorField("Balance Sheet",	"ADV_DEP",	"Advances, deposits, and ownership interests in and advances to companies",	"Advances and deposits that offer benefits in the future.",	"Millions"),
    IndicatorField("Balance Sheet",	"LTERM_RCV",	"Long-term receivables",	"Notes, loans, accounts and other receivables expected in more than one year.",	"Millions"),
    IndicatorField("Balance Sheet",	"INVTY_LTERM",	"Inventory - Long-term",	"Inventories classified as long term rather than short term",	"Millions"),
    IndicatorField("Balance Sheet",	"GOODWILL_INTANG_ASSET_TOT",	"Goodwill and intangable assets - Total",	"The sum of all intangible asset fields",	"Millions"),
    IndicatorField("Balance Sheet",	"DEF_CHARGE_NON_CURR",	"Deferred charges - Non-current",	"Non-current costs that are deferred and amortized over time or prepaid and earned at a later date.",	"Millions"),
    IndicatorField("Balance Sheet",	"DEF_TAX_ASSET_LTERM",	"Deferred tax assets - Long-term",	"A non-current asset created by a difference between accounting for income tax purposes and financial reporting purposes.",	"Millions"),
    IndicatorField("Balance Sheet",	"ASSET_DISCONT_OPER_LTERM",	"Assets of discontinued operations - Long-term",	"The aggregate value of non-current assets from business segments that a company has disposed of or wants to dispose of in the near future.",	"Millions"),
    IndicatorField("Balance Sheet",	"PENSION_POST_RETIRE_ASSET",	"Pension and post-retirement asset",	"Assets for employee post-retirement benefits.",	"Millions"),
    IndicatorField("Balance Sheet",	"OTHER_LTERM_ASSET",	"Other long-term assets",	"Field containing the sum of all non-current assets that cannot be standardized into another field as well as those that are aggregated by the company because materially, they are too small to list separately.",	"Millions"),
    IndicatorField("Balance Sheet",	"TOT_LTERM_ASSET",	"Total long-term assets",	"The sum of all assets classified as non-current",	"Millions"),
    IndicatorField("Balance Sheet",	"TOT_ASSET",	"Total assets",	"The sum of all assets on a company's balance sheet.",	"Millions"),
    IndicatorField("Balance Sheet",	"NOTE_PAY",	"Notes payable",	"Amounts owed that are documented by printed notes.",	"Millions"),
    IndicatorField("Balance Sheet",	"ACCT_PAY", "Accounts payable",	"Amounts payable to vendors extended as a line of credit for normal business purchases.",	"Millions"),
    IndicatorField("Balance Sheet",	"DIV_PAY",	"Dividends payable",	"Amounts owed to shareholders after a dividend has been declared by the board of directors.",	"Millions"),
    IndicatorField("Balance Sheet",	"OTHER_PAY",	"Other payables",	"Miscellaneous payables.",	"Millions"),
    IndicatorField("Balance Sheet",	"ACCRUED_EXP",	"Accrued expenses",	"Expenses that have been incurred but not paid.",	"Millions"),
    IndicatorField("Balance Sheet",	"OTHER_ACCRUED_EXP",	"Other accrued expenses",	"Accrued liabilities classified as 'other' or that cannot be classified into another standard field.",	"Millions"),
    IndicatorField("Balance Sheet",	"CURR_PORTION_DEBT",	"Current portion debt",	"The portion of debt which is payable in the upcoming year.",	"Millions"),
    IndicatorField("Balance Sheet",	"CURR_PORTION_CAP_LEASE",	"Current portion of capital lease",	"The portion of long term capital leases which is due in the upcoming year.",	"Millions"),
    IndicatorField("Balance Sheet",	"CURR_PORTION_TAX_PAY",	"Current portion of taxes payable",	"The portion of income taxes which is payable in the upcoming year.",	"Millions"),
    IndicatorField("Balance Sheet",	"DEFER_REVNU_CURR",	"Deferred revenue - Current",	"Revenue collected or promised for which the reporting company still has to provide future goods or services.",	"Millions"),
    IndicatorField("Balance Sheet",	"DEFER_TAX_LIAB_CURR",	"Deferred tax liabilitiy - Current",	"A liability created by a difference between accounting for income tax purposes and financial reporting purposes.",	"Millions"),
    IndicatorField("Balance Sheet",	"LIAB_DISCONT_OPER_CURR",	"Liabilities of discontinued operations - Current",	"The aggregate value of current liabilities from business segments that a company has disposed of or wants to dispose of in the near future.",	"Millions"),
    IndicatorField("Balance Sheet",	"OTHER_CURR_LIAB",	"Other current liabilities",	"Field containing the sum of all current liabilities that cannot be standardized into another field as well as those that are aggregated by the company because materially, they are too small to list separately.",	"Millions"),
    IndicatorField("Balance Sheet",	"TOT_CURR_LIAB",	"Total current liabilities",	"The sum of all liabilities classified as current for having maturities of less than one year.",	"Millions"),
    IndicatorField("Balance Sheet",	"TOT_LTERM_DEBT",	"Total long-term debt",	"The sum of all long term debt fields",	"Millions"),
    IndicatorField("Balance Sheet",	"DEFER_REVNU_NON_CURR",	"Deferred revenue - Non-current",	"Revenue collected or promised for which the reporting company still has to provide future goods or services.",	"Millions"),
    IndicatorField("Balance Sheet",	"PENSION_POST_RETIRE_LIAB",	"Pension and post-retirement liability",	"Liabilities for employee post-retirement benefits.",	"Millions"),
    IndicatorField("Balance Sheet",	"DEFER_TAX_LIAB_LTERM",	"Deferred tax liability - Long-term",	"A liability created by a difference between accounting for income tax purposes and financial reporting purposes.",	"Millions"),
    IndicatorField("Balance Sheet",	"MAND_REDEEM_PREF_SEC_SUBSID",	"Mandatory redeemable preferred securities of subsidiary",	"Mandatorily redeemable securities of subsidiary companies.",	"Millions"),
    IndicatorField("Balance Sheet",	"PREF_STOCK_LIAB",	"Preferred stock - Liabilities",	"Preferred stock that is classified as a liability because of certain ownership and return criteria.",	"Millions"),
    IndicatorField("Balance Sheet",	"MIN_INT",	"Minority interest",	"A liability arising from consolidation of subsidiary entities into the financial statements of the parent company. Assets of subsidiaries are included in the balance sheet of the parent company and the remaining portion of the subsidiaries ownership is classified as a liability.",	"Millions"),
    IndicatorField("Balance Sheet",	"LIAB_DISC_OPER_LTERM",	"Liabilities of discontinued operations - Long-term",	"The aggregate value of long-term liabilities from business segments that a company has disposed of or wants to dispose of in the near future.",	"Millions"),
    IndicatorField("Balance Sheet",	"OTHER_NON_CURR_LIAB",	"Other non-current liabilities",	"Field containing the sum of all non-current liabilities that cannot be standardized into another field as well as those that are aggregated by the company because materially, they are too small to list separately.",	"Millions"),
    IndicatorField("Balance Sheet",	"TOT_LTERM_LIAB",	"Total long-term liabilities",	"The sum of all non-current liabilities",	"Millions"),
    IndicatorField("Balance Sheet",	"TOT_LIAB",	"Total liabilities",	"The total value of all possible claims against the corporation.",	"Millions"),
    IndicatorField("Balance Sheet",	"TOT_PREF_STOCK",	"Total preferred stock",	"The sum of all preferred equity fields.",	"Millions"),
    IndicatorField("Balance Sheet",	"COMM_STOCK_NET",	"Common stock net",	"The value of common equity ownership.",	"Millions"),
    IndicatorField("Balance Sheet",	"ADDTL_PAID_IN_CAP",	"Additional paid-in capital",	"The excess over par value paid for common securities.",	"Millions"),
    IndicatorField("Balance Sheet",	"RETAIN_EARN_ACCUM_DEFICIT",	"Retained earnings (accumulated deficit)",	"Profits reinvested in the corporation after dividends have been paid out.",	"Millions"),
    IndicatorField("Balance Sheet",	"EQUITY_EQUIV",	"Equity equivalent",	"Miscellaneous forms of instruments representing equity.",	"Millions"),
    IndicatorField("Balance Sheet",	"TREAS_STOCK",	"Treasury stock",	"Common shares bought back by the issueing company and held in its treasury",	"Millions"),
    IndicatorField("Balance Sheet",	"COMPR_INCOME",	"Comprehensive income",	"The change in net assets of a business enterprise during a period from transactions and other events and circumstances from nonowner sources. It includes all changes in equity during a period except those resulting from investments by owners and distributions to owners.",	"Millions"),
    IndicatorField("Balance Sheet",	"DEF_COMPSN",	"Deferred compensation",	"An amount of stock set aside for purchase through employee compensation deferral plans.",	"Millions"),
    IndicatorField("Balance Sheet",	"OTHER_SHARE_HOLDER_EQUITY",	"Other share holders equity",	"Field containing the sum of all current assets that cannot be standardized into another field as well as those that are aggregated by the company because materially, they are too small to list separately.",	"Millions"),
    IndicatorField("Balance Sheet",	"TOT_COMM_EQUITY",	"Total common equity",	"The sum of all common equity items",	"Millions"),
    IndicatorField("Balance Sheet",	"TOT_SHARE_HOLDER_EQUITY",	"Total share holder equity",	"The sum of preferred and common equity items",	"Millions"),
    IndicatorField("Balance Sheet",	"TOT_LIAB_SHARE_HOLDER_EQUITY",	"Total liabilities and share holders equity",	"The total of all liabilities and shareholders' equity.",	"Millions"),
    IndicatorField("Balance Sheet",	"COMM_SHARES_OUT",	"Common shares outstanding",	"The number of class A shares currently held by investors.",	"Millions"),
    IndicatorField("Balance Sheet",	"PREF_STOCK_SHARES_OUT",	"Preferred stock - Number of shares outstanding",	"The number of preferred stock shares currently held by investors.",	"Millions"),
    IndicatorField("Balance Sheet",	"TANG_STOCK_HOLDER_EQUITY",	"Tangible stock holders equity",	"The value shareholders equity less intangible assets",	"Millions"),
    IndicatorField("Cash Flow Statement",	"NET_INCOME_LOSS",	"Net income/loss",	"The company's total income or loss before preferred stock dividends, taken from the Income Statement",	"Millions"),
    IndicatorField("Cash Flow Statement",	"TOT_DEPREC_AMORT_CASH_FLOW",	"Total depreciation and amortization - Cash flow",	"The total amount of depreciation and amortization listed on the Cash Flows Statement",	"Millions"),
    IndicatorField("Cash Flow Statement",	"OTHER_NON_CASH_ITEM",	"Other non-cash items",	"Miscellaneous non-cash adjustments to Net income.",	"Millions"),
    IndicatorField("Cash Flow Statement",	"TOT_NON_CASH_ITEM",	"Total non-cash items",	"The total of all non-cash charges adjusting Net Income on the Cash Flows Statement",	"Millions"),
    IndicatorField("Cash Flow Statement",	"CHANGE_ACCT_RCV",	"Change in accounts receivable",	"The increase or decrease in accounts receivable for the given period.",	"Millions"),
    IndicatorField("Cash Flow Statement",	"CHANGE_INVTY",	"Change in inventories",	"The increase or decrease in a company's inventories for the period.",	"Millions"),
    IndicatorField("Cash Flow Statement",	"CHANGE_ACCT_PAY",	"Change in accounts payable",	"The increase or decrease in trade payables for the given period.",	"Millions"),
    IndicatorField("Cash Flow Statement",	"CHANGE_ACCT_PAY_ACCRUED_LIAB",	"Change in accounts payable and accrued liability",	"Changes in accounts payable and accrued liabilities",	"Millions"),
    IndicatorField("Cash Flow Statement",	"CHANGE_INCOME_TAX",	"Change in income taxes",	"Changes in income tax accounts",	"Millions"),
    IndicatorField("Cash Flow Statement",	"CHANGE_ASSET_LIAB",	"Change in assets/liabilities",	"Represents any other changes in assets/liabilities",	"Millions"),
    IndicatorField("Cash Flow Statement",	"TOT_CHANGE_ASSET_LIAB",	"Total change in assets/liabilities",	"The sum of all line items in the Asset/Liability section of the Cash Flows Statement",	"Millions"),
    IndicatorField("Cash Flow Statement",	"OPER_ACTIVITY_OTHER",	"Operating activities - Other",	"The net amount of items a company reports that are too small to report separately. Additionally, this field holds the sum of items a company reports that cannot be assigned to any other standardized field.",	"Millions"),
    IndicatorField("Cash Flow Statement",	"CASH_FLOW_OPER_ACTIVITY",	"Cash flow from operating activities",	"A company's cash flows from operations.",	"Millions"),
    IndicatorField("Cash Flow Statement",	"NET_CHANGE_PROP_PLANT_EQUIP",	"Net change in property, plant, and equipment",	"The overall change in capital expenditures and sales of plant, property and equipment. This field is used if a company does not report separately sales and purchases of plant, property and equipment or is calculated as the sum of purchases and sales of PP&E",	"Millions"),
    IndicatorField("Cash Flow Statement",	"NET_CHANGE_INTANG_ASSET",	"Net change in intangible assets",	"The overall change from the sale and purchase of intangible assets including patents, rights and capitalized software.",	"Millions"),
    IndicatorField("Cash Flow Statement",	"NET_ACQ_DIVST",	"Net acquisitions/divestitures",	"The total change in cash resulting from both investments in businesses and sales of businesses or business segments.",	"Millions"),
    IndicatorField("Cash Flow Statement",	"NET_CHANGE_STERM_INVST",	"Net change in short-term investments",	"The net cash flows from the sale and purchase of investments defined to be short-term, generally with maturities of less than one year from the purchase date.",	"Millions"),
    IndicatorField("Cash Flow Statement",	"NET_CHANGE_LTERM_INVST",	"Net change in long-term investments",	"The net cash flows from the sale and purchase of investments with maturities greater than one year.",	"Millions"),
    IndicatorField("Cash Flow Statement",	"NET_CHANGE_INVST_TOT",	"Net change in investments - Total",	"The total change in long term and short term investments",	"Millions"),
    IndicatorField("Cash Flow Statement",	"INVST_ACTIVITY_OTHER",	"Investing activities - Other",	"The net amount of items a company reports that are too small to report separately. Additionally, this field holds the sum of items a company reports that cannot be assigned to any other standardized field in the investing activities section of the Cash Flows Statement",	"Millions"),
    IndicatorField("Cash Flow Statement",	"CASH_FLOW_INVST_ACTIVITY",	"Cash flow from investing activities",	"The total change in cash resulting from a companies investments",	"Millions"),
    IndicatorField("Cash Flow Statement",	"NET_LTERM_DEBT",	"Net long-term debt",	"The net amount of long term debt issued and repaid. This field is either calculated as the sum of the long term debt fields or used if a company does not report debt issued and repaid separately",	"Millions"),
    IndicatorField("Cash Flow Statement",	"NET_CURR_DEBT",	"Net current debt",	"The net amount of debt repaid and issued with short-term maturities.",	"Millions"),
    IndicatorField("Cash Flow Statement",	"DEBT_ISSUE_RETIRE_NET_TOT",	"Debt issuance/retirement net - Total",	"The total amount of short term and long term borrowings repaid and issued.",	"Millions"),
    IndicatorField("Cash Flow Statement",	"NET_COMM_EQUITY_ISSUED_REPURCH",	"Net common equity issued/repurchased",	"The net dollar amount of transactions to issue and repurchase common stock.",	"Millions"),
    IndicatorField("Cash Flow Statement",	"NET_PREF_EQUITY_ISSUED_REPURCH",	"Net preferred equity issued/repurchased",	"The net dollar amount of transactions to issue and repurchase preferred stock.",	"Millions"),
    IndicatorField("Cash Flow Statement",	"NET_TOT_EQUITY_ISSUED_REPURCH",	"Net total equity issued/repurchased",	"The sum of all preferred and common equity transactions regarding a company's own stock.",	"Millions"),
    IndicatorField("Cash Flow Statement",	"TOT_COMM_PREF_STOCK_DIV_PAID",	"Total common and preferred stock dividends paid",	"The cash outflow for all company dividends paid out to preferred and common shareholders.",	"Millions"),
    IndicatorField("Cash Flow Statement",	"FIN_ACTIVITY_OTHER",	"Financial activities - Other",	"The net amount of items a company reports that are too small to report separately. Additionally, this field holds the sum of items a company reports that cannot be assigned to any other standardized field in the financing activities section of the Cash Flows Statement.",	"Millions"),
    IndicatorField("Cash Flow Statement",	"CASH_FLOW_FIN_ACTIVITY",	"Cash flow from financial activities",	"The net amount of cash transactions used in funding activities",	"Millions"),
    IndicatorField("Cash Flow Statement",	"FGN_EXCHANGE_RATE_ADJ",	"Foreign exchange rate adjustment",	"The change in cash arising from fluctuating foreign exchange rates.",	"Millions"),
    IndicatorField("Cash Flow Statement",	"DISC_OPER_MISC_CASH_FLOW_ADJ",	"Discontinued operations and miscellaneous cash flow adjustments",	"The net amount of change in cash arising from the discontinuation of segments or any other adjustments to cash that do not fit in any other sections.",	"Millions"),
    IndicatorField("Cash Flow Statement",	"INCR_DECR_CASH",	"Increase/decrease in cash",	"The total change in cash for the company over the given period.",	"Millions"),
    IndicatorField("Cash Flow Statement",	"BEG_CASH",	"Beginning cash",	"The amount of cash reported by the company on its previous statement.",	"Millions"),
    IndicatorField("Cash Flow Statement",	"END_CASH",	"End cash",	"The amount of cash held by the company for the given period.",	"Millions"),
    IndicatorField("Cash Flow Statement",	"STOCK_BASED_COMPSN",	"Stock-based compensation",	"The estimated market value of stock options, warrants and other stock-based compensation given to employees and/or vendors",	"Millions"),
    IndicatorField("Cash Flow Statement",	"COMM_STOCK_DIV_PAID",	"Common stock dividends paid",	"The cash outflow for dividends paid on a company's common stock",	"Millions"),
    IndicatorField("Cash Flow Statement",	"PREF_STOCK_DIV_PAID",	"Preferred stock dividends paid",	"The cash outflow for dividends paid on a company's preferred stock",	"Millions"),
    IndicatorField("Supplementary Cash Flow",	"TOT_DEPREC_AMORT_QD",	"Total depreciation and amortization -Quarterly discrete",	"Quarterly discrete version of total depreciation and amortization from the cash flow statement",	"Millions"),
    IndicatorField("Supplementary Cash Flow",	"STOCK_BASED_COMPSN_QD",	"Stock-based compensation - Quarterly discrete",	"Quarterly discrete version of stock-based compensation from the cash flow statement",	"Millions"),
    IndicatorField("Supplementary Cash Flow",	"CASH_FLOW_OPER_ACTIVITY_QD",	"Cash flow from operating activities - Quarterly discrete",	"Quarterly discrete version of total cash flow from operations",	"Millions"),
    IndicatorField("Supplementary Cash Flow",	"NET_CHANGE_PROP_PLANT_EQUIP_QD",	"Net change in property, plant, and equipment - Quarterly discrete",	"Quarterly discrete version of the net change in property, plant & equipment from the cash flow statement",	"Millions"),
    IndicatorField("Supplementary Cash Flow",	"COMM_STOCK_DIV_PAID_QD",	"Common stock dividends paid - Quarterly discrete",	"Quarterly discrete version of total common stock dividends paid from the cash flow statement",	"Millions"),
    IndicatorField("Supplementary Cash Flow",	"PREF_STOCK_DIV_PAID_QD",	"Preferred stock dividends paid - Quarterly discrete",	"Quarterly discrete version of total preferred stock dividends paid from the cash flow statement",	"Millions"),
    IndicatorField("Supplementary Cash Flow",	"TOT_COMM_PREF_STOCK_DIV_QD",	"Total common and preferred stock dividends paid - Quarterly discrete",	"Quarterly discrete version of total common and preferred stock dividends paid from the cash flow statement",	"Millions"),
  )

}
